<?php

declare(strict_types=1);

namespace Atom\Head;

use Atom\Head\Enum\OpenGraphTag;
use Atom\Head\Enum\ColorScheme;
use Atom\Head\Head;

/**
 * HeadGenerate class
 *
 * This class is responsible for generating the HTML head section of a web page.
 *
 * It provides a single method, autoGenerate, which takes a Head object, an array of options, and an object of data as parameters.
 *
 * The autoGenerate method generates the HTML head section based on the options and data provided.
 *
 * @final
 */
final class HeadGenerate
{
    /**
     * Generate the HTML head section of a web page.
     *
     * This method takes a Head object, an array of options, and an object of data as parameters.
     *
     * It generates the HTML head section based on the options and data provided.
     *
     * @param Head $head The Head object to generate the HTML head section from.
     * @param array $option An array of options for generating the HTML head section.
     * @param object $data An object of data to use when generating the HTML head section.
     * @return string The generated HTML head section.
     */
    public static function autoGenerate(Head $head, array $option, object $data): string
    {
        $title = $data->title;
        $description = $data->description;
        if ($option['autoGenerateTitle']) {
            $title = "{{headTitle}} {$option['separator']} " . $title;
        }
        if ($option['autoGenerateDescription']) {
            $description = "{{headDescription}} {$option['separator']} " . $description;
        }

        $head->charset()
        ->viewport()
        ->title($title)
        ->description($description)
        ->favicon($data->image . $option['iconSvg'])
        ->shortcutIcon($data->image . $option['iconIco'])
        ->icon($data->image . $option['iconPng'])
        ->robots($option['robot'])
        ->author("Atom Contributors")
        ->authoringTool("Atom")
        ->generator("Atom 2.0")
        ->base($data->uri)
        ->themeColor($option['colorTheme'], $option['isDarkMode'])
        ->colorScheme($option['colorScheme'])
        ->canonical($data->uri . $data->canonical)
        ->manifest($data->manifest);

        if ($option['autoGenerateOG']) {
            $head->ogTitle($title)
            ->ogDescription($description)
            ->ogSiteName($data->title)
            ->ogType("website")
            ->ogUrl($data->uri . $data->canonical)
            ->ogImage($data->image . $option['iconSvg'])
            ->ogImageWidth($option['iconWith'])
            ->ogImageHeight($option['iconHeight']);
        }

        if ($option['autoGenerateApple']) {
            $head->appleMobileWebAppTitle($data->title)
            ->appleMobileWebAppStatusBarStyle("black-translucent")
            ->appleTouchIcon($data->image . $option['iconPng'])
            ->appleTouchStartupImage($data->image . $option['iconPng']);
        }

        if ($data->script['scheme']) {
            $head->scriptText($data->script['scheme'], true);
        }

        return $head->build();
    }

    /**
     * This method returns the value of the autoCompleted status.
     *
     * @return string The value of the autoCompleted status.
     */
    public static function autoCompleted(): string
    {
        return "not compleated";
    }
}
