<?php

declare(strict_types=1);

namespace Tests\Atom\Head;

use PHPUnit\Framework\TestCase;
use Atom\Head\HeadGenerate;
use Atom\Head\Head;

class HeadGenerateTest extends TestCase
{
    public function testAutoGenerateReturnsString()
    {
        $head = $this->createMock(Head::class);
        $option = [
            'autoGenerateTitle' => false,
            'autoGenerateDescription' => false,
            'separator' => ' - ',
            'iconSvg' => '.svg',
            'iconIco' => '.ico',
            'iconPng' => '.png',
            'robot' => 'index,follow',
            'colorTheme' => '#ffffff',
            'isDarkMode' => false,
            'colorScheme' => 'light',
            'autoGenerateOG' => false,
            'autoGenerateApple' => false,
            'iconWith' => 1200,
            'iconHeight' => 630
        ];
        $data = (object) [
            'title' => 'Test Title',
            'description' => 'Test Description',
            'image' => '/images/',
            'uri' => 'https://example.com',
            'canonical' => '/page',
            'manifest' => '/manifest.json',
            'script' => [
                'scheme' => 'var customScheme = true;'
            ]
        ];

        // Mock the Head object to avoid actual HTML generation
        $head->method('build')->willReturn('<head></head>');

        $result = HeadGenerate::autoGenerate($head, $option, $data);
        
        $this->assertIsString($result);
    }

    public function testAutoGenerateWithAutoGenerateTitle()
    {
        $head = $this->createMock(Head::class);
        $option = [
            'autoGenerateTitle' => true,
            'autoGenerateDescription' => false,
            'separator' => ' | ',
            'iconSvg' => '.svg',
            'iconIco' => '.ico',
            'iconPng' => '.png',
            'robot' => 'index,follow',
            'colorTheme' => '#ffffff',
            'isDarkMode' => false,
            'colorScheme' => 'light',
            'autoGenerateOG' => false,
            'autoGenerateApple' => false,
            'iconWith' => 1200,
            'iconHeight' => 630
        ];
        $data = (object) [
            'title' => 'Test Title',
            'description' => 'Test Description',
            'image' => '/images/',
            'uri' => 'https://example.com',
            'canonical' => '/page',
            'manifest' => '/manifest.json',
            'script' => [
                'scheme' => 'var customScheme = true;'
            ]
        ];

        // Mock the Head object to avoid actual HTML generation
        $head->method('build')->willReturn('<head></head>');
        
        // We can't easily test the method chain directly without a more complex setup
        // But we'll make sure it doesn't error
        $result = HeadGenerate::autoGenerate($head, $option, $data);
        
        $this->assertIsString($result);
    }

    public function testAutoGenerateWithAutoGenerateOG()
    {
        $head = $this->createMock(Head::class);
        $option = [
            'autoGenerateTitle' => false,
            'autoGenerateDescription' => false,
            'separator' => ' - ',
            'iconSvg' => '.svg',
            'iconIco' => '.ico',
            'iconPng' => '.png',
            'robot' => 'index,follow',
            'colorTheme' => '#ffffff',
            'isDarkMode' => false,
            'colorScheme' => 'light',
            'autoGenerateOG' => true,
            'autoGenerateApple' => false,
            'iconWith' => 1200,
            'iconHeight' => 630
        ];
        $data = (object) [
            'title' => 'Test Title',
            'description' => 'Test Description',
            'image' => '/images/',
            'uri' => 'https://example.com',
            'canonical' => '/page',
            'manifest' => '/manifest.json',
            'script' => [
                'scheme' => 'var customScheme = true;'
            ]
        ];

        // Mock the Head object to avoid actual HTML generation
        $head->method('build')->willReturn('<head></head>');

        $result = HeadGenerate::autoGenerate($head, $option, $data);
        
        $this->assertIsString($result);
    }

    public function testAutoGenerateWithAutoGenerateApple()
    {
        $head = $this->createMock(Head::class);
        $option = [
            'autoGenerateTitle' => false,
            'autoGenerateDescription' => false,
            'separator' => ' - ',
            'iconSvg' => '.svg',
            'iconIco' => '.ico',
            'iconPng' => '.png',
            'robot' => 'index,follow',
            'colorTheme' => '#ffffff',
            'isDarkMode' => false,
            'colorScheme' => 'light',
            'autoGenerateOG' => false,
            'autoGenerateApple' => true,
            'iconWith' => 1200,
            'iconHeight' => 630
        ];
        $data = (object) [
            'title' => 'Test Title',
            'description' => 'Test Description',
            'image' => '/images/',
            'uri' => 'https://example.com',
            'canonical' => '/page',
            'manifest' => '/manifest.json',
            'script' => [
                'scheme' => 'var customScheme = true;'
            ]
        ];

        // Mock the Head object to avoid actual HTML generation
        $head->method('build')->willReturn('<head></head>');

        $result = HeadGenerate::autoGenerate($head, $option, $data);
        
        $this->assertIsString($result);
    }

    public function testAutoGenerateWithScript()
    {
        $head = $this->createMock(Head::class);
        $option = [
            'autoGenerateTitle' => false,
            'autoGenerateDescription' => false,
            'separator' => ' - ',
            'iconSvg' => '.svg',
            'iconIco' => '.ico',
            'iconPng' => '.png',
            'robot' => 'index,follow',
            'colorTheme' => '#ffffff',
            'isDarkMode' => false,
            'colorScheme' => 'light',
            'autoGenerateOG' => false,
            'autoGenerateApple' => false,
            'iconWith' => 1200,
            'iconHeight' => 630
        ];
        $data = (object) [
            'title' => 'Test Title',
            'description' => 'Test Description',
            'image' => '/images/',
            'uri' => 'https://example.com',
            'canonical' => '/page',
            'manifest' => '/manifest.json',
            'script' => [
                'scheme' => 'var customScheme = true;'
            ]
        ];

        // Mock the Head object to avoid actual HTML generation
        $head->method('build')->willReturn('<head></head>');

        $result = HeadGenerate::autoGenerate($head, $option, $data);
        
        $this->assertIsString($result);
    }

    public function testAutoCompletedReturnsString()
    {
        $result = HeadGenerate::autoCompleted();
        
        $this->assertIsString($result);
        $this->assertEquals("not compleated", $result);
    }
}
